name: Jsite
favicon: null
layout_spectrum: 0.5921940880361944
typography_spectrum: 0.374682453693822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6848252161871642
  lightness: 0.7189767137169838
  saturation: 0.8132244637235999
  rhythmicContrast: 0.11768297851085663
purpose: []
